backend:
  name: github
  repo: lucasayb/the-ssg-central
  branch: main
  site_domain: thessgcentral.com

media_folder: "static/uploads" # Adjust based on your media storage location
public_folder: "/uploads" # URL path for accessing media

collections:
  - name: "posts" # This is the name used in the URL
    label: "Post" # This is the singular name of the content type for the UI
    folder: "content/post" # The folder where your posts markdown files will be saved
    create: true # Allows users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template for new posts
    fields: # List of fields for the front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Hidden", name: "hidden", widget: "boolean", default: false}
      - {label: "Comments", name: "comments", widget: "boolean", default: true}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Weight", name: "weight", widget: "number", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "categories" # This should match the name of your categories collection
        searchFields: ["title"] # This defines what fields to search in the categories collection to list options
        valueField: "title" # This defines which field from the categories collection to store as the value in the posts
        displayFields: ["title"] # This defines what fields to display in the CMS for selection
        required: false

  - name: "categories" # This is the name used in the URL for categories
    label: "Category" # This is the singular name of the category content type for the UI
    folder: "content/categories" # The folder where your category markdown files will be saved
    create: true # Allows users to create new documents in this collection
    slug: "{{slug}}" # Filename template for new categories
    fields: # List of fields for the category front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - label: "Style"
        name: "style"
        widget: "object"
        fields:
          - {label: "Background", name: "background", widget: "string"}
          - {label: "Color", name: "color", widget: "string"}